name: examen01
description: "AplicaciÃ³n Flutter con Firebase para boletas de alquiler"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.0
  
  # Utilidades
  intl: ^0.20.2
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.10
  google_fonts: ^5.0.0
  google_maps_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true